= Migration Toolkit for Applications by Red Hat (MTA) Distribution

== Overview

This project builds the MTA distribution ZIP file. It includes all launch scripts, batch files, libraries, JARs, add-ons, and configuration files for running MTA.

This projects contains dependencies on the following projects, which must be built first.

* https://github.com/windup/windup-rulesets[windup-rulesets]: This project contains the MTA rules.
* https://github.com/windup/windup[windup]: This project contains the Windup core source code.

A script to build this project and its dependencies (above) can be found here: https://github.com/windup/windup-local-build-scripts[windup-local-build-scripts].

More detailed instructions are located here: https://github.com/windup/windup/wiki/Dev-Build-from-Source[Build Windup from Source].

== Build the Project

To build this project, type:

        mvn clean install

If you want to build this project using SNAPSHOTs, add the `settings.xml` file to the command line:

        mvn -s settings.xml clean install

This creates a `mta-distribution-<VERSION>-offline.zip` file in the `mta-distribution/target/` directory.

== Additional Resources

* Follow the https://github.com/windup/windup/wiki/Get-Involved[Get Involved] in Windup wiki.

