name: Windup downstream distribution

on:
  workflow_dispatch:
    inputs:
      theme:
        description: "Theme to build: mta, tackle, or mtr"
        required: true
      tag:
        description: "Branch name or Tag name"
        required: true

  schedule:
    - cron: "0 0 * * *"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: windup/windup-rulesets
          path: windup-rulesets
          ref: ${{ github.event.inputs.tag }}
      - uses: actions/checkout@v2
        with:
          repository: windup/windup
          path: windup
          ref: ${{ github.event.inputs.tag }}
      - uses: actions/checkout@v2
        with:
          path: windup-distribution
          ref: ${{ github.event.inputs.tag }}

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          java-package: jdk
          cache: 'maven'

      - name: Build Windup
        run: mvn clean install -DskipTests -Ddownstream=${{ github.event.inputs.theme }} -f windup/
      - name: Build Windup Rulesets
        run: mvn clean install -DskipTests -Ddownstream=${{ github.event.inputs.theme }} -f windup-rulesets/
      - name: Build Windup distribution
        run: mvn clean install -DskipTests -Ddownstream=${{ github.event.inputs.theme }} -f windup-distribution/

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: cli
          path: windup-distribution/target/*-offline.zip


