name: Windup PR builder

on:
  pull_request:
    branches:
      - master
      - 'releases/**'
  push:
    branches:
      - master
      - 'releases/**'

jobs:
  windup-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          repository: windup/windup
          ref: ${{ github.base_ref }}
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          java-package: jdk
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-windup-build-${{ github.sha }}
      - name: Build Windup on JDK 11
        run: mvn -B clean install -DskipTests

  windup-rulesets-build:
    runs-on: ubuntu-latest
    needs: [windup-build]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          repository: windup/windup-rulesets
          ref: ${{ github.base_ref }}
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          java-package: jdk
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-windup-rulesets-build-${{ github.sha }}
          restore-keys: |
            maven-windup-build-${{ github.sha }}
      - name: Build Windup Rulesets
        run: mvn -B clean install -DskipTests

  windup-cli-build:
    strategy:
      fail-fast: false
      matrix:
        jdk-distribution: [ temurin ]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    needs: [windup-rulesets-build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: ${{ matrix.jdk-distribution }}
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: .m2
          key: maven-windup-cli-build-${{ github.sha }}
          enableCrossOsArchive: true
          restore-keys: |
            maven-windup-rulesets-build-${{ github.sha }}
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.7
      - name: Maven build
        run: mvn clean install -DskipTests -B -s build/settings.xml -Dmaven.repo.local=.m2
